export default {
  allOrderData: [
    {
      title: 'Order',
      order: '#1035',
      date: 'Tuesday at 06: 09pm',
      customer: 'Test Test',
      payment: '',
      fulfilment: 'Unfulfilled',
      total: '120.00',
    },
    {
      title: 'Date',
      order: '#1035',
      date: 'Tuesday at 06: 09pm',
      customer: 'Test Test',
      payment: 'Paid',
      fulfilment: 'Unfulfilled',
      total: '120.00',
    },
    {
      title: 'Customer',
      order: '#1035',
      date: 'Tuesday at 06: 09pm',
      customer: 'Test Test',
      payment: 'Pending',
      fulfilment: 'Unfulfilled',
      total: '120.00',
    },
    {
      title: 'Payment',
      order: '#1035',
      date: 'Tuesday at 06: 09pm',
      customer: 'Test Test',
      payment: 'Paid',
      fulfilment: 'Fulfilled',
      total: '120.00',
    },
    {
      title: 'Fulfilment',
      order: '#1035',
      date: 'Tuesday at 06: 09pm',
      customer: 'Test Test',
      payment: 'Pending',
      fulfilment: 'Unfulfilled',
      total: '120.00',
    },
    {
      title: 'Total',
      order: '#1035',
      date: 'Tuesday at 06: 09pm',
      customer: 'Test Test',
      payment: 'Pending',
      fulfilment: 'Unfulfilled',
      total: '120.00',
    },
    {
      order: '#1035',
      date: 'Tuesday at 06: 09pm',
      customer: 'Test Test',
      payment: 'Pending',
      fulfilment: 'Unfulfilled',
      total: '120.00',
    },
    {
      order: '#1035',
      date: 'Tuesday at 06: 09pm',
      customer: 'Test Test',
      payment: 'Paid',
      fulfilment: 'Fulfilled',
      total: '120.00',
    },
    {
      order: '#1035',
      date: 'Tuesday at 06: 09pm',
      customer: 'Test Test',
      payment: 'Pending',
      fulfilment: 'Unfulfilled',
      total: '120.00',
    },
    {
      order: '#1035',
      date: 'Tuesday at 06: 09pm',
      customer: 'Test Test',
      payment: 'Paid',
      fulfilment: 'Fulfilled',
      total: '120.00',
    },
    {
      order: '#1035',
      date: 'Tuesday at 06: 09pm',
      customer: 'Test Test',
      payment: 'Paid',
      fulfilment: 'Fulfilled',
      total: '120.00',
    },
    {
      order: '#1035',
      date: 'Tuesday at 06: 09pm',
      customer: 'Test Test',
      payment: 'Paid',
      fulfilment: 'Fulfilled',
      total: '120.00',
    },
  ],
};
